s!(1 or 2)!(DDS_READ_SAMPLE_STATE + DDS_NOT_READ_SAMPLE_STATE)!
s!(4 or 8)!(DDS_NEW_VIEW_STATE + DDS_NOT_NEW_VIEW_STATE)!
s!(16 or 32 or 64)!(DDS_ALIVE_INSTANCE_STATE + DDS_NOT_ALIVE_DISPOSED_INSTANCE_STATE + DDS_ANY_INSTANCE_STATE )!
